app_name: testblox
desc: oops..
domain: tstblx.win
dsc_invite: 5H6u2zR8qn
debug: false
quotes: 
  - is $_SERVER["REMOTE_ADDR"] your IP?
  - If buying is not owning, then piracy isn't stealing
  - custom client src ftw
  - happy men's mental health month (if you are reading this in june)
  - NO GOONING.
  - Never goon.
  - this revival needs invite keys bozo
  - :3
  - also known as sigmablox
  - there is now 3 versions of testblox
  - SPREAD. BUBONIC. PLAGUE!!!
  - â“
  - â“ğŸ¤«ğŸ”ğŸŸâ„¢ğŸ§¼ğŸ§½ğŸ˜ŠğŸ’•ğŸ˜˜ğŸ‘ŒğŸ˜’ğŸ˜ğŸ¤£ğŸ˜‚âœŒğŸ¤·â€â™‚ï¸ğŸ¤·â€â™€ï¸ğŸ¤¦â€â™‚ï¸ğŸ¤¦â€â™€ï¸ğŸ™ŒğŸ‘ğŸ˜ğŸ‘ğŸ˜œğŸ’–ğŸ˜¢ğŸ¶ğŸ˜ğŸ˜‰ğŸ¤
  #- more secure than actual roblox #neva ill think about it
  - privacy-focused

invitekeys:
  name: tstblx
  randlength: 32

backup: false
behind_proxy: false # CloudFlare Mode ACtivated

session:
  name: TESTBLO_SECURITY # if you change this, it will log people out
  expires: 31536000000 # this is in ms which is a year

currency:
  name: pizza
  starter: 80

# what else do i call these
rules:
  tos: 
    - no hacking.
    - no putting out doxxes or doxxing.

# server default 
locale: en-us
language: en-us

# http config
port: 80

# use nginx noob
#ssl: true