app_name: testblox
desc: testblox is a webclient revival aiming to recreate older versions
domain: tstblx.win
dsc_invite: pHPBy8FvAY
debug: true
production: false # else development
log_file: false
quotes: 
  - is $_SERVER["REMOTE_ADDR"] your IP?
  - If buying is not owning, then piracy isn't stealing
  - custom client src ftw
  - happy men's mental health month (if you are reading this in june)
  - NO GOONING.
  - Never goon.
  - this revival needs invite keys bozo
  - :3
  - also known as sigmablox
  - there is now 3 versions of testblox
  - SPREAD. BUBONIC. PLAGUE!!!
  - â“
  - â“ğŸ¤«ğŸ”ğŸŸâ„¢ğŸ§¼ğŸ§½ğŸ˜ŠğŸ’•ğŸ˜˜ğŸ‘ŒğŸ˜’ğŸ˜ğŸ¤£ğŸ˜‚âœŒğŸ¤·â€â™‚ï¸ğŸ¤·â€â™€ï¸ğŸ¤¦â€â™‚ï¸ğŸ¤¦â€â™€ï¸ğŸ™ŒğŸ‘ğŸ˜ğŸ‘ğŸ˜œğŸ’–ğŸ˜¢ğŸ¶ğŸ˜ğŸ˜‰ğŸ¤
  #- more secure than actual roblox #neva ill think about it
  - privacy-focused
  - pidar kurva suka nahui
  - aÅ¡ esu gejus ğŸ³ï¸â€ğŸŒˆğŸ³ï¸â€ğŸŒˆğŸ³ï¸â€ğŸŒˆğŸ³ï¸â€ğŸŒˆğŸ³ï¸â€ğŸŒˆğŸ³ï¸â€ğŸŒˆğŸ³ï¸â€ğŸŒˆğŸ³ï¸â€ğŸŒˆğŸ³ï¸â€ğŸŒˆ

invitekeys:
  name: tstblx
  randlength: 32

backup: false
behind_proxy: false # CloudFlare Mode ACtivated

admin_panel:
  # dont add a "/" suffix, please
  path: "/admin" # change for whatever reason idk
  troll: true
  #only if troll is true you can make it redirect to whatever page
  troll_url: //pornhub.com

session:
  name: TESTBLO_SECURITY # if you change this, it will log people out
  expires: 31536000000 # this is in ms which is a year

# defaults
user:
  status: "i'm new to testblox!"

currency:
  name: pizza
  starter: 80

# what else do i call these
rules:
  tos: 
    - no hacking.
    - no putting out doxxes or doxxing.

# server default 
locale: en-us
lang: english
timezone: Europe/Vilnius

database: 
  host: 127.0.0.1
  port: 5432
  database: "testblox-v3"
  username: "postgres"
  password: "qqqq"  
  ssl: false # useless if on the same server as webserver
  log_queries: false

discord:
  prefix: "t:"
  
views:
  folder: "views"

rcc:
  # recommend you make this very long
  user_agent: "testblox/rcc; testblox/cURL; Roblox/WinInet"

# http config
http:
  port: 8021

# use nginx noob
#ssl: true